<?php
/**
Temporary mapping of Activa to Netsuite,  This will be deprecated once Activa impements 
this new version of the Netsuite API

 */
$aMap = array(

		
		//'AuthErrorMessage' => 'custbody_web_payment_error',
		'AdditionalCustomizations' => '_additionalcustomizations',
		'AuthorizationCode' => 'authcode',
		'BillingCompanyName' => 'companyname',
		'BillingAddress1' => 'addr1',
		'BillingAddress2' => 'addr2',
		'BillingCity' => 'city',
		'BillingState' => 'state',
		'BillingProvince' => 'province',
		//'BillingProvince(Other)' => null,
		'BillingZip' => 'zip',
		'BillingCountry' => 'country',
		'BillingPhone' => 'phone',
		'CCType' => 'paymentmethod',
		'CCFullName' => 'ccname',
		'CCNumber' => 'ccnumber',
		'CCMonthExpiration' => '_ccexpiremonth',
		'CCYearExpiration' => '_ccexpireyear',
		'CustomerFirstName' => 'firstname',
		'CustomerLastName' => 'lastname',
		'CustomerE-mail' => 'email',
		'CustomerAccountType' => 'isperson',
		'CustomerCompanyName' => 'companyname',
		'CustomerFotomail' => 'custentity_fotomail',
		'CustomerID' => 'custentity_customer_source_id',
		'Engraving' => 'custbody_logorequired',
		'EngravingDetails' => '_engravingdetails',
		'entityid' => 'entityid',  // REMOVE FOR LIVE TOOL ONLY
		//'EventDate' => 'custbody_event_date',
		//'GiftMessage' => 'message', ///??????
		'GiftCertificateAmount' => '_gcamount',
		'HandlingAmount' => 'handlingcost',
		//'How did you hear about us' => null,
		'ImageSKU' => 'custcol162',
		'ItemDiscountAmount' => 'discounttotal',
		'ItemDiscountCodes' => 'discountitem',
		'Items' => 'description',
		'Message' => 'custbody_textrequired',
		'MessageDetails' => '_messagedetails',
		'MultiShipTo' => 'ismultishipto',
		'NewGiftCertificateCode' => 'giftcertnumber',
		//'NewGiftCertificateAmount' => ,
		'NewGiftCertificateFromName' => 'giftcertfrom',
		//'NewGiftCertificateFromEmail' => ,
		'NewGiftCertificateToName' => 'giftcertrecipientname',
		'NewGiftCertificateToEmail' => 'giftcertrecipientemail',
		'NewGiftCertificateMessage' => 'giftcertmessage',
		'OptionValues' => 'custbody_comments',
		'OrderItemSubtotal' => 'subtotal',
		//'OrderItemTotal' => 'amount',
		'OrderParcelNumber' => '_order_parcel_number',
		'OrderSource' => '_source',
		//'OrderStatus' => 'orderstatus',
		'OrderNumber' => 'custbody_order_source_id',
		'OrderDate' => 'trandate',
		'OrderDiscountAmount' => 'discounttotal',
		'OrderTotal' => 'total',
		'PaymentMethod' => '_paymentmethod_flag',
		//'PurchaseOrderNumber' => 'otherrefnum',
		'PickTicketNotes' => 'custbody_pickticketnotes',
		'PromoCode' => '_promocode',
		'PromoCodeAmount' => '_promoamount',
		'ProduceInStore' => 'custcol_produce_in_store',
		'ProductSKU' => 'item',
		'Qty' => 'quantity',
		//'RequestToken' => 'pnrefnum',
		'SetupFee' => 'setup',
		'ShippingMethod' => 'shipmethod',
		//'SalespersonSalespersonID' => 'salesrep',
		'StorePickup' => 'custcol_store_pickup',
		'ShippingAmount' => 'shippingcost',
		'ShippingAddress' => 'shipaddress',
		'ShippingFirstName' => '_attention1',
		'ShippingLastName' => '_attention2',
		'ShippingCompanyName' => '_companyname',
		'ShippingAddress1' => 'addr1',
		'ShippingAddress2' => 'addr2',
		'ShippingCity' => 'city',
		'ShippingState' => 'state',
		'ShippingProvince' => 'province',
		'ShippingZip' => 'zip',
		'ShippingCountry' => 'country',
		'ShippingPhone' => 'phone',
		'SourceCode' => 'custbody_source_code',
		'TaxAmount' => 'taxtotal',
		'TaxRate' => 'taxrate',
		'TransactionKey' => 'pnrefnum',
		'UnitPrice' => 'rate'
);


$aItemMap = array(
		'Items',
		'ProductSKU',
		'ImageSKU',
		'Qty',
		'UnitPrice',
		'OrderItemSubtotal',
		'OrderItemTotal',
		'SetupFee',
		'ItemDiscountAmount',
		'ItemDiscountCodes',
		'Engraving',
		'EngravingDetails',
		'Message',
		'MessageDetails',
		'AdditionalCustomizations',
		'ProduceInStore',
		'NewGiftCertificateCode',
		'NewGiftCertificateAmount',
		'NewGiftCertificateFromName',
		'NewGiftCertificateFromEmail',
		'NewGiftCertificateToName',
		'NewGiftCertificateToEmail',
		'NewGiftCertificateMessage',
		'StorePickup',
		'OptionValues',
		'ShippingMethod',
		'ShippingFirstName',
		'ShippingLastName',
		'ShippingCompanyName',
		'ShippingAddress1',
		'ShippingAddress2',
		'ShippingCity',
		'ShippingState',
		'ShippingProvince',
		//'ShippingProvince(Other)',
		'ShippingZip',
		'ShippingCountry','ShippingPhone');

$aAddressMap = array(
		'BillingCompanyName',
		'BillingAddress1',
		'BillingAddress2',
		'BillingCity',
		'BillingState',
		'BillingProvince',
		//'BillingProvince(Other)',
		'BillingZip',
		'BillingCountry',
'BillingPhone');
		
		
		$aCustomerMap = array(
				'CustomerID',
				'CustomerFirstName',
				'CustomerLastName',
				'CustomerE-mail',
				'CustomerAccountType',
				'CustomerCompanyName',
				'CustomerFotomail',
		'entityid'); // REMOVE FOR FINAL VERSION TOOL ONLY
		
		$aOrderMap = array (
				'OrderSource',
				'OrderNumber',
				'OrderDate',
				'OrderStatus',
				'CustomerID',
				'TaxAmount',
				'TaxRate',
				'ShippingAmount',
				'HandlingAmount',
				'OrderDiscountAmount',
				'OrderTotal',
				'PurchaseOrderNumber',
				'SalespersonSalespersonID',
				'MultiShipTo',
				'EventDate',
				'GiftMessage',
				'GiftCertificateAmount',
				'SourceCode',
				'PromoCode',
				'PromoCodeAmount',
				//'How did you hear about us' => null,
				'TransactionKey',
				'AuthorizationCode',
				//'RequestToken' => 'pnrefnum',
				//'AuthErrorMessage',
				'CCType',
				'CCFullName',
				'CCNumber',
				'CCMonthExpiration',
				'CCYearExpiration',
				'PickTicketNotes',
				'PaymentMethod'
		);
		
		
		$aMap3 = array(
				'HandlingAmount' => 'handlingcost',
				'Items' => 'description',
				'ProductSKU' => 'item',
				'ImageSKU' => 'custcol162',
				'Qty' => 'quantity',
				'UnitPrice' => 'rate',
				'OrderItemSubtotal' => 'subtotal',
				'OrderItemTotal' => 'total',
				'SetupFee' => 'setup',
				'ItemDiscountAmount' => 'discounttotal',
				'ItemDiscountCodes' => 'discountitem',
				'Engraving' => 'custbody_logorequired',
				'EngravingDetails' => '_engravingdetails',
				'Message' => 'custbody_textrequired',
				'MessageDetails' => '_messagedetails',
				'AdditionalCustomizations' => '_additionalcustomizations',
				'NewGiftCertificateCode' => 'giftcertnumber',
				//'NewGiftCertificateAmount' => ,
				'NewGiftCertificateFromName' => 'giftcertfrom',
				//'NewGiftCertificateFromEmail' => ,
				'NewGiftCertificateToName' => 'giftcertrecipientname',
				'NewGiftCertificateToEmail' => 'giftcertrecipientemail',
				'NewGiftCertificateMessage' => 'giftcertmessage',
				'OptionValues' => 'custbody_comments',
				'ProduceInStore' => 'custcol_produce_in_store',
				'StorePickup' => 'custcol_store_pickup',
				'ShippingAmount' => 'shippingcost',
				'ShippingAddress' => 'shipaddress',
				'ShippingFirstName' => '_attention1',
				'ShippingLastName' => '_attention2',
				'ShippingCompanyName' => '_companyname',
				'ShippingAddress1' => 'addr1',
				'ShippingAddress2' => 'addr2',
				'ShippingCity' => 'city',
				'ShippingState' => 'state',
				'ShippingProvince' => 'province',
				'ShippingZip' => 'zip',
				'ShippingCountry' => 'country',
				'ShippingPhone' => 'phone',
				'ShippingAddress' => 'shipaddress'
		);
		
		
		$aMap2 = array(
		
				'BillingCompanyName' => 'companyname',
				'BillingAddress1' => 'addr1',
				'BillingAddress2' => 'addr2',
				'BillingCity' => 'city',
				'BillingState' => 'state',
				'BillingProvince' => 'province',
				//'BillingProvince(Other)' => null,
				'BillingZip' => 'zip',
				'BillingCountry' => 'country',
				'BillingPhone' => 'phone',
				'ShippingCompanyName' => 'companyname',
				'ShippingAddress1' => 'addr1',
				'ShippingAddress2' => 'addr2',
				'ShippingCity' => 'city',
				'ShippingState' => 'state',
				'ShippingProvince' => 'province',
				'ShippingZip' => 'zip',
				'ShippingCountry' => 'country',
				'ShippingPhone' => 'phone'
		);
		