<style>
body {
	background-image:
		url('public/images/cool_background_image.gif');
	background-repeat: repeat;
}
.max_results{
font-style:italic;
}

h2{
margin-bottom:5px;
}
#main_div {
	float: left;
	margin-right: 60px;
	margin-left: 30px;
}

#main {
	width: 700px;
}

#stats {
	width: 400px;
	overflow: auto;
}

.td_status:hover {
	cursor: pointer;
}
#cssmenu ul {
	margin: 0;
	padding: 0;
	list-style-type: none;
	width: auto;
	position: relative;
	display: block;
	height: 30px;
	font-size: 12px;
	font-weight: bold;
	background: transparent url(public/images/nav_bg.png) repeat-x top left;
	font-family: Arial, Helvetica, sans-serif;
	border-bottom: 1px solid #000000;
	border-top: 1px solid #000000;
}

#cssmenu li {
	display: block;
	float: left;
	margin: 0;
	padding: 0;
}

#cssmenu li a {
	display: block;
	float: left;
	color: #999999;
	text-decoration: none;
	font-weight: bold;
	padding: 8px 20px 0 20px;
}

#cssmenu li a:hover {
	color: #FFFFFF;
	height: 22px;
	background: transparent url(public/images/nav_bg.png) 0px -30px
		no-repeat;
}

#cssmenu li.active a {
	display: inline;
	height: 22px;
	background: transparent url(public/images/nav_bg.png) 0px -30px
		no-repeat;
	float: left;
	margin: 0;
}
#last {
float:right;
}
</style>
<link href="public/scripts/jquery.tablesorter/themes/blue/style.css" type="text/css" rel="stylesheet" />
<link href="public/scripts/jquery.tablesorter/addons/pager/jquery.tablesorter.pager.css" type="text/css" rel="stylesheet" />
<script src="public/scripts/jquery.tablesorter/jquery-latest.js"></script>
<script type="text/javascript" src="public/scripts/jquery.tablesorter/jquery.tablesorter.js"></script>
<script type="text/javascript" src="public/scripts/jquery.tablesorter/addons/pager/jquery.tablesorter.pager.js"></script>  
<script type="text/javascript">
$(document).ready(function(){


	
		        $("#main").tablesorter({widthFixed: true, widgets: ['zebra']}).tablesorterPager({container: $("#pager")}); 
		
	
	var sPath=window.location.pathname;
	var sPage = sPath.substring(sPath.lastIndexOf('/') + 1);
	
	$('a[href="' + sPage + '"]').parent().addClass('active');
	
});
</script>

<div id='cssmenu'>
	<ul class='mainmenu'>
		<li><a href='index'><span>Process Log</span> </a></li>
		<li><a href='orderqueue'><span>Order Queue</span> </a></li>
		<li><a href='userlog'><span>Account Log</span> </a></li>
		<li><a href='pos'><span>Live POS</span> </a></li>
	<li id="last">
	<form id="search" name="search" method="post" action="search">
	<input type="text" name="q" id="q" />
	<input type="submit" value="Search"/>
	</form>
	</li>
	</ul>
</div>
