<style>
#cssmenu ul {
	margin: 0;
	padding: 0;
	list-style-type: none;
	width: auto;
	position: relative;
	display: block;
	height: 30px;
	font-size: 12px;
	font-weight: bold;
	background: transparent url(public/images/nav_bg.png) repeat-x top left;
	font-family: Arial, Helvetica, sans-serif;
	border-bottom: 1px solid #000000;
	border-top: 1px solid #000000;
}

#cssmenu li {
	display: block;
	float: left;
	margin: 0;
	padding: 0;
}

#cssmenu li a {
	display: block;
	float: left;
	color: #999999;
	text-decoration: none;
	font-weight: bold;
	padding: 8px 20px 0 20px;
}

#cssmenu li a:hover {
	color: #FFFFFF;
	height: 22px;
	background: transparent url(public/images/nav_bg.png) 0px -30px
		no-repeat;
}

#cssmenu li.active a {
	display: inline;
	height: 22px;
	background: transparent url(public/images/nav_bg.png) 0px -30px
		no-repeat;
	float: left;
	margin: 0;
}
</style>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

<script type="text/javascript">
$(document).ready(function(){

	var sPath=window.location.pathname;
	var sPage = sPath.substring(sPath.lastIndexOf('/') + 1);
	
	$('a[href="' + sPage + '"]').parent().addClass('active');
	
});
</script>

<div id='cssmenu'>
	<ul class='mainmenu'>
		<li><a href='index'><span>Process Log</span> </a></li>
		<li><a href='order_queue'><span>Order Queue</span> </a></li>
		<li><a href='postcsvform'><span>Post CSV</span> </a></li>
		<li><a href='nstest'><span>Create Order</span> </a></li>
		<li class='last'><a href='#'><span>Contact</span> </a></li>
	</ul>
</div>
