<style>
body,button,td,select,textarea,input {
	font-family: Tahoma, Geneva, sans-serif;
	color: #5C7499;
	font-size: 8pt;
	text-decoration: none;
}

h4 {
	margin-bottom: 2px;
	margin-top: 2px;
}

h2 {
	display: inline;
}

.outer_wrapper {
	border: 1px solid black;
	width: 1030px;
	margin: auto;
	padding-bottom: 10px;
	margin-bottom: 20px;
	margin-top: 20px;
	-moz-border-radius: 15px;
	border-radius: 5px;
	overflow: auto;
	background-color: #F5F6FA;
}

body {
	background-image:
		url('/Threaded/Panel/public/images/cool_background_image.gif');
	background-repeat: repeat;
}

.wrapper {
	width: 1000px;
	clear: both;
	margin: auto;
}

.item_wrapper {
	width: 900px;
	clear: both;
	margin: auto;
	border: 1px solid black;
	-moz-border-radius: 15px;
	border-radius: 5px;
	height: 200px;
	padding: 5px;
	margin-top: 10px;
	margin-bottom: 10px;
}

.clear {
	clear: both;
	width: 1000px;
	margin: auto;
	margin-bottom: 50px;
}

.right {
	float: right;
}

.left {
	float: left;
}

.collapse_link {
	cursor: pointer;
	cursor: hand;
}

.element_div {
	margin-right: 20px;
	height: 37px;
}

label {
	display: block;
}

#thread_staus {
	vertical-align: middle;
	line-height: 25px;
	width: 550px;
	height: 25px;
	background-position: 150px 0px;
	background-repeat: no-repeat;
}

.result_div {
	margin: 10px;
	width: 900px;
	max-height: 100px;
	overflow: auto;
	display: none;
	word-wrap: break-word;
	padding: 5px;
	border: 1px solid black;
	-moz-border-radius: 15px;
	border-radius: 5px;
}

button {
	margin-right: 20px;
}

.flipped {
	transform: scale(1, -1);
	-moz-transform: scale(1, -1);
	-webkit-transform: scale(1, -1);
	-o-transform: scale(1, -1);
	-khtml-transform: scale(1, -1);
	-ms-transform: scale(1, -1);
}

.netsuite_link {
	text-decoration: none;
	margin-left: 50px;
}

@keyframes blink { 0% {
	color: red;
}

100%{color:black;}
}
@-webkit-keyframes blink { 0% {
	color: red;
}
100%{color:black;}
}

.system_error {
	font-weight: bold;
	background-color: rgba(255, 0, 0, 0.3);
	width: 400px;
	padding: 5px;
	border: 1px solid black;
	-moz-border-radius: 15px;
	border-radius: 5px;
	display: inline;
	-webkit-animation: blink 3s linear infinite;
	-moz-animation: blink 3s linear infinite;
	animation: blink 3s linear infinite;
}

.error {
	background-color: rgba(255, 0, 0, 0.3);
}

.warn {
	background-color: rgba(255, 255, 0, 0.3);
}

.success {
	background-color: rgba(0, 128, 0, 0.3);
}

.modal {
	display: none;
	position: fixed;
	z-index: 1000;
	top: 0;
	left: 0;
	height: 100%;
	width: 100%;
	background: rgba(255, 255, 255, .8)
		url('http://i.stack.imgur.com/FhHRx.gif') 50% 50% no-repeat;
}

/* When the body has the loading class, we turn
   the scrollbar off with overflow:hidden */
body.loading {
	overflow: hidden;
}

/* Anytime the body has the loading class, our
   modal element will be visible */
body.loading .modal {
	display: block;
}
</style>

<script
	src="/Threaded/Panel/public/scripts/jquery.form.js"></script>
<script type="text/javascript">
<!--
var parent;
var salesOrder = {};
salesOrder.customer = {};
salesOrder.order = {};
addressbook = {};
addressbook.shipping = {};
addressbook.billing = {};
salesOrder.order.item = [];
salesOrder.customer.addressbook = addressbook;
var tempItems = {};
var netsuite_order_link = 'https://system.sandbox.netsuite.com/app/accounting/transactions/salesord.nl?id=';
var netsuite_customer_link = 'https://system.sandbox.netsuite.com/app/common/entity/custjob.nl?id=';

$(document).ready(function(){

	//socket_server_alive();
	reCalculate();
	
	//var id = setInterval(socket_server_alive, 60000);

	
	$('#server_status_button').click(function(){
		socket_server_alive();
	});
	
	$('#items, #order').on('change', 'input, select:not(select[name="item"])', function() {
		reCalculate();	
	});


	
	$('#items').on('change', 'select[name="item"]', function() {

		var target_div = $(this).parent().parent();

$('> div > input[name="description"]', target_div).val( ( $('option:selected',this).attr('description') ) );
$('> div > input[name="rate"]', target_div).val( ( $('option:selected',this).attr('price') ) );

var quantity = ( $('> div > input[name="quantity"]', target_div).val() < 1 )? 1: $('> div > input[name="quantity"]', target_div).val();
$('> div > input[name="quantity"]', target_div).val( quantity );


reCalculate();

	});

	
$('.collapse_link').click(function(){

	 if( $( ' > img',this).hasClass('flipped') ) {
		 $(' > img',this).removeClass('flipped');
	 }else {
		 $(' > img',this).addClass('flipped');
	 }
	 
	$(this).parent().parent().each(function(){
		
		 $('div.element_div, h4',this).toggle(function(){
			
		 });	
	});	
});


	
$( 'button[name="show_json"]' ).click( function(){

	$('div[name="json"]').toggle();

});

$('#items').on('click', 'a.remove_item', function() {
	var removeObj = $(this).parent();
	if( $('#items > div').length == 1 ) {
		alert('An Order MUST Have at Least One Item');
		return( false );
	}
	$(removeObj).remove();
	

	$('div.item_wrapper').each( function(){
		$(this).children('h4').html('Item: ' + ($(this).index()+1));
	});
	
	return( false );
});

$( '#add_item' ).click( function(){

	var newItem = $('div[name="item"]').first().clone();
	var ns = 'x' + Math.floor((Math.random()*10000)+1);
	
	$('#items').append( $(newItem) );
    $('input, select', newItem ).attr('ns', ns);
	$('div[name="item"]').last().children('input, select').attr('ns', ns);
	 $('div[name="item"]:last > div > input').val('');
	 $('div[name="item"]:last > div > select').prop("selectedIndex",0)
    $('div.item_wrapper').each( function(){
		$(this).children('h4').html('Item: ' + ($(this).index()+1));
	});
		
	$('select[name="istaxable"]:last option:eq(2)').prop('selected', true);
	$('select[name="custcol_produce_in_store"]:last option:eq(1)').prop('selected', true);
	$('select[name="custcol_store_pickup"]:last option:eq(1)').prop('selected', true);
	$('select[name="isclosed"]:last option:eq(1)').prop('selected', true);
	$('select[name="isestimate"]:last option:eq(1)').prop('selected', true);
	$('select[name="istaxable"]').prop('disabeld', true);
		
	 $("html, body").animate({ scrollTop: $(document).height() }, "slow");

});





$('#csv_upload').ajaxForm({ dataType: 'json', success : function(data) {
	$('input').val('');
	setFormValues(data.customer);
	setFormValues(data.order);
    
}}); 






$('#submit_order').click(function() {

	
	var tempItems = {};
	salesOrder.order.item = [];
	salesOrder['_netsuite'] = ( $('#send_netsuite').is( ":checked" ) === true ) ? 1: 0;

	if( salesOrder['_netsuite'] == 1 & $('#entityid').val() == 99999 ){

		var answer = confirm('Send to Netsuite is Set to "true", but the Customer "entityid" is Set to the Test Id.\nThe Netsuite Order Record Will Not Post!\nDo You Want to Continue?')
		if (answer){
			
		}
		else{
			return( false );
		}
	}
	
	$('.result_div, .system_error').empty().hide();
	
	$('div.wrapper > div.element_div, div.item_wrapper > div.element_div').each(function(){
		parent = $(this).parent().attr('name');
		
		$( 'input, select', this ).each( function(){
			var ns = $(this).attr('ns');
			
			switch(parent){

			case('item'):
			case('custcol_produce_in_store'):
			case('custcol_store_pickup'):

				
					if( typeof(tempItems[ns]) !== 'object'   ){
						tempItems[ns] = {};
						salesOrder.order.item.push(tempItems[ns]);
					}
					tempItems[ns][$(this).attr('id')] = $(this).val();
				break;

			case('address'):
			
					addressbook[ns][$(this).attr('id')] = $(this).val();
				break;

			default:
				salesOrder[parent][$(this).attr('id')] = $(this).val();
				break;

			}
			
			
		});
	});
	

		 $('body').addClass("loading");
	var request = $.ajax({
		url: "/Threaded/Panel/postorder",
		type: "POST",
		data: { data : salesOrder },
		dataType: "json"
		});
	
		request.done(function( msg ) {
			 $('body').removeClass("loading");
		if( msg.customer.success === true ){ 
			var target_a = $('#customer.wrapper > div.results > div.success');
			$(target_a).html('SUCCESS - New Netsuite Internal Id: ' + msg.customer.netsuite.record_id ).show();
			$('#entityid').val( msg.customer.netsuite.record_id ); 
			if( msg.customer.netsuite.record_id != 99999 ){
				$(target_a).append('<a target="_blank" href="'+ netsuite_customer_link + msg.customer.netsuite.record_id +'" class="netsuite_link">Netsuite Record</a>');
			}
			}
		if( msg.customer.warn != null ){ $('#customer.wrapper > div.results > div.warn').html(msg.customer.warn.join("<br>")).show(); }
		if( msg.customer.error != null ){ $('#customer.wrapper > div.results > div.error').html(msg.customer.error.join("<br>")).show();	}
		if( msg.customer.netsuite.error != null ){ $('#customer.wrapper > div.results > div.error').html( msg.customer.netsuite.error.code + ' - ' + msg.customer.netsuite.error.details ).show();}
		
		if( msg.order.success === true  ){ 
			var target_a = $('#order.wrapper > div.results > div.success');
			$(target_a).html('SUCCESS - New Netsuite Internal Id: ' + msg.order.netsuite.record_id ).show();
			if( msg.order.netsuite.record_id != 99999 ){
				$(target_a).append('<a target="_blank" href="'+ netsuite_order_link + msg.order.netsuite.record_id +'" class="netsuite_link">Netsuite Record</a>');
			}
		}
		if( msg.order.warn != null ){ $('#order.wrapper > div.results > div.warn').html(msg.order.warn.join("<br>")).show();}
		if( msg.order.error != null ){ $('#order.wrapper > div.results > div.error').html(msg.order.error.join("<br>")).show();}
		if( msg.order.netsuite.error != null ){ $('#order.wrapper > div.results > div.error').html( msg.order.netsuite.error.code + ' - ' + msg.order.netsuite.error.details ).show();}	
		
		if( msg.system.error != null ){ $('#system_error').html(msg.system.error).show();}	

		$('#customer.wrapper > div.results > div[name="json"]').html(msg.customer.json);
		$('#order.wrapper > div.results > div[name="json"]').html(msg.order.json);
		
		});
		request.fail(function( jqXHR, textStatus ) {
		alert( "Request failed: " + textStatus );
		$('body').removeClass("loading");
		});
});
	
});


function setFormValues( dataObj, ns, selector ){

	for( i in dataObj ){
		

		var value = dataObj[i];

		switch( true ){


		case( selector != null ):

			$('[id="' + i + '"]', selector ).val(value);

			break;
		

		case( i == 'item'  ):

		var items = dataObj[i];
		//var newItem = $('div[name="item"]').first().clone();
		//setFormValues( items.shift(), null, $('div[name="item"]').first() );
		
		for( var a=0; a<(items.length); a++ ){
			
			var newItem = $('div[name="item"]').first().clone();
			if( a == 0 ){
				$('#items').empty();
			}
			var ns = 'x' + Math.floor((Math.random()*10000)+1);
		
			$('#items').append( $(newItem) );
	    	$('input, select', newItem ).attr('ns', ns);
			$('div[name="item"]').last().children('input, select').attr('ns', ns);
			 $('div[name="item"]:last > div > input').val('');
			 $('div[name="item"]:last > div > select').prop("selectedIndex",0)
			setFormValues(items[a], ns, $('div[name="item"]').last() );
		}			
		
		$('select[name="istaxable"]').prop('disabeld', true);
		 $('div.item_wrapper').each( function(){
				$(this).children('h4').html('Item: ' + ($(this).index()+1));
			});

			
			break;
		
		case( ns != null ):
			$('#' + i + '[ns="'+ ns +'"]' ).val(value);
			break;
		
		case( i == 'addressbook' ):
		var billingAddress = dataObj[i][0];	
			
		if( typeof(dataObj[i][1]) != 'undefined' ){
			setFormValues(dataObj[i][1], 'shipping');
		} else {
			setFormValues( billingAddress, 'shipping' );
		}
		setFormValues( billingAddress, 'billing' );
			
			break;
						
		case( typeof(dataObj[i]) == 'object' ):
			setFormValues(dataObj[i]);
			break;
		
		case(value == 'T' || value == 'F' ):
				value = ( value == 'T' )?1:0;
		default:
			$('#' + i ).val(value);
			break;
		}
				
		
	}
}



function socket_server_alive(){
	
	var start = new Date().getTime();
	
	var request = $.ajax({
		url: "/SocketServer/ServerAlive.php",
		type: "POST",
		data: {},
		dataType: "json"
		});
	
		request.done(function( msg ) {
			$('#thread_staus').css('background-image','url(stop_lights.jpg)');
			var end = new Date().getTime();
			var requestTime = (end - start);
			
			switch( true ){

			case( requestTime > 5000 ):
				$('#thread_staus').css('background-position','150px -25px');
				break;

			case( msg == 1 ):
				$('#thread_staus').css('background-position','150px 0px');
			
				break;
			}
			$('#thread_staus').html('&nbsp;&nbsp;'+(requestTime/1000).toFixed(2) + ' sec Response Time').append( '<br>Last Checked: ' + new Date().getHours()+':'+ new Date().getMinutes() );
		});

		request.fail(function( jqXHR, textStatus ) {
			$('#thread_staus').css('background-position','150px -50px');
			$('#thread_time').html('Connection Failed: ' + textStatus);
			});
	}


function reCalculate() {
	
	// Hack to fix ns property on item select box
	$('select[name="item"]').last().attr('ns', $('input[name="amount"]').last().attr('ns'));

switch( $('#_paymentmethod_flag').val() ) {

case( 'cash' ):
case( 'wire' ):
case( 'check' ):
	$('#paymentmethod option').show();
	$('#paymentmethod option[value="'+  $('#_paymentmethod_flag').val() +'"]').prop('selected', true);
	$('#paymentmethod').prop('disabled', true);
	break;

case( 'pos' ):
	var cards = [ "visa", "mastercard", "amex", "discover" ];
	$('#paymentmethod option').each( function() {

		if($.inArray($(this).val(), cards) >= 0 ){
		$(this).hide();	
		}
		
	});
	//$('#paymentmethod option').show();
	$('#paymentmethod option').eq(0).prop('selected', true);
	break;
	
case('creditcard'):
	$('#paymentmethod option').show();
	$('#paymentmethod').prop('disabled', false);
var noncards = [ "cash","wire","check","pos" ];
var cards = [ "visa", "mastercard", "amex", "discover" ];
$('#paymentmethod option').each( function() {

	if($.inArray($(this).val(), noncards) >= 0 ){
	$(this).hide();	
	}
	
});
if($.inArray($('#paymentmethod option:selected').val(), cards) < 0 ){
	$('#paymentmethod option:selected').prop('selected', false);
	$('#paymentmethod').eq(0).prop('selected', true);
	}

	break;


}

	var order_total = 0;
	var order_tax = 0;
	
	$('#items > div[name="item"]').each( function() {
		
		var quantity = $( 'div > input[name="quantity"]',this ).val();
		var item_price = $('div > input[name="rate"]',this ).val();
		var item_total = ( item_price * quantity );

		$('div > input[name="amount"]',this ).val(( item_price * quantity ).toFixed(2) );
		
		
		order_total += item_total;
		order_tax += ( $('#taxrate').val() * item_total );
		

	});
	$('#total').val( order_total.toFixed(2));
	$('#taxtotal').val( (order_tax/100).toFixed(2));
}

//-->
</script>
</head>
<body>
	<?php echo( $this->html ) ?>
	<div class="modal">
		<!-- Place at bottom of page -->
	</div>
</body>
</html>
