<?php $ignore = array() ?>
<?php $title = 'POS Test Results' ?>
<div id="main_div">
	<h2>LivePOS Import Conversion Results</h2>
	<span class="max_results">*<?php echo( PANEL_MAX_RESULTS) ?> Results Returned</span>
<table id="main" class="tablesorter" style="width:900px">
<thead>
	<tr>
		<?php foreach( array_keys($this->aOrders[0]) as $sHeading ):
		if( in_array(  $sHeading, $ignore ) ){
			continue;
		}?>
		<th><?php echo( ucwords( str_replace( '_',' ', strtolower( $sHeading ) ) ) ) ?>
		</th>
		<?php endforeach ?>
	</tr>
	</thead>
	<tbody>
	<?php foreach( $this->aOrders as $aOrder ): ?>
	<tr>
		<?php foreach( $aOrder as $sKey => $mValue ):?>
		<td class="td_<?php echo( $sKey ) ?>" align="center" title="<?php echo( $title ) ?>"><?php echo( $mValue ) ?>
		</td>
		<?php $title = 'Completed Successfully' ?>
		<?php endforeach ?>
	</tr>
	<?php endforeach ?>
	</tbody>
</table>
<div class="pager" id="pager">
	<form>
		<img class="first" src="public/images/first.png">
		<img class="prev" src="public/images/prev.png">
		<input type="text" class="pagedisplay">
		<img class="next" src="public/images/next.png">
		<img class="last" src="public/images/last.png">
		<select class="pagesize">
			<option value="10" selected="selected">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>
<br>
<span>ALL Totals are Pre Tax Amounts</span>
<br>
<br>
</div>
<div><br></div>


<div id="stats">
<h3>Insert Test Orders</h3>

	<table id="stats_table" class="tablesorter">
		<thead>
			<tr>
				<?php foreach( array_keys($this->testStats[0]) as $sHeading ):?>
				<th><?php echo( ucwords( str_replace( '_',' ', strtolower( $sHeading ) ) ) ) ?>
				</th>
				<?php endforeach ?>
			</tr>
		</thead>
		<tbody>
			<?php foreach( $this->testStats as $aOrder ): 
			
			?>
			<tr>
				<?php foreach( $aOrder as $sKey => $mValue ):?>
				
				<td class="td_<?php echo( $sKey ) ?>" align="center"><?php echo( trim($mValue) ) ?>
				</td>

				<?php endforeach ?>

			</tr>
			<?php endforeach ?>
		</tbody>
	</table>
</div>