<?php $ignore = array( 'order_errors', 'order_warnings', 'customer_errors', 'customer_warnings', 'process_id' ) ?>
<?php $title = 'Completed Successfully' ?>
<style>
body {
	background-image:
		url('public/images/cool_background_image.gif');
	background-repeat: repeat;
}
#main {
width: 800px;

}
.td_status:hover{
cursor: pointer;
}



</style>
<table id="main" class="tablesorter">
<thead>
	<tr>
		<?php foreach( array_keys($this->aOrders[0]) as $sHeading ):
		if( in_array(  $sHeading, $ignore ) ){
			continue;
		}?>
		<th><?php echo( ucwords( str_replace( '_',' ', strtolower( $sHeading ) ) ) ) ?>
		</th>
		<?php endforeach ?>
	</tr>
	</thead>
	<tbody>
	<?php foreach( $this->aOrders as $aOrder ): ?>
	<tr>
		<?php foreach( $aOrder as $sKey => $mValue ):
		if( in_array(  $sKey, $ignore ) ){
			continue;
		}
		if($sKey == 'status' && $mValue == 'error'){
			$title = '';
			$title .= ( $aOrder['customer_errors'] != '')?"Customer Errors:\n" .$aOrder['customer_errors']."\n":'';
			$title .= ( $aOrder['order_errors'] != '')?"Order Errors:\n". $aOrder['order_errors']:'';
		}
		?>
		<td class="td_<?php echo( $sKey ) ?>" align="center" title="<?php echo( $title ) ?>"><?php echo( $mValue ) ?>
		</td>
		<?php $title = 'Completed Successfully' ?>
		<?php endforeach ?>
		
	</tr>
	<?php endforeach ?>
	</tbody>
</table>
<div class="pager" id="pager">
	<form>
		<img class="first" src="public/images/first.png">
		<img class="prev" src="public/images/prev.png">
		<input type="text" class="pagedisplay">
		<img class="next" src="public/images/next.png">
		<img class="last" src="public/images/last.png">
		<select class="pagesize">
			<option value="10" selected="selected">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>