<div id="main_div">
	<h2>NetSuite Account Log</h2>
	<span class="max_results">*<?php echo( PANEL_MAX_RESULTS) ?> Results Returned</span>
<table id="main" class="tablesorter">
<thead>
	<tr>
		<?php foreach( array_keys($this->aOrders[0]) as $sHeading ):?>
		<th><?php echo( ucwords( str_replace( '_',' ', strtolower( $sHeading ) ) ) ) ?>
		</th>
		<?php endforeach ?>
	</tr>
	</thead>
	<tbody>
	<?php foreach( $this->aOrders as $aOrder ): ?>
	<tr>
		<?php foreach( $aOrder as $sKey => $mValue ): ?>
		<td class="td_<?php echo( $sKey ) ?>" align="center"><?php echo( $mValue ) ?>
		</td>
		<?php endforeach ?>
		
	</tr>
	<?php endforeach ?>
	</tbody>
</table>
<div class="pager" id="pager">
	<form>
		<img class="first" src="public/images/first.png">
		<img class="prev" src="public/images/prev.png">
		<input type="text" class="pagedisplay">
		<img class="next" src="public/images/next.png">
		<img class="last" src="public/images/last.png">
		<select class="pagesize">
			<option value="10" selected="selected">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
			<option value="40">40</option>
		</select>
	</form>
</div>
</div>
<h3><?php echo( PANEL_SUMMARY_RESULTS) ?> Day Summary</h3>

<div id="stats">

	<table id="stats_table" class="tablesorter">
		<thead>
			<tr>
				<?php foreach( array_keys($this->queueStats[0]) as $sHeading ):?>
				<th><?php echo( ucwords( str_replace( '_',' ', strtolower( $sHeading ) ) ) ) ?>
				</th>
				<?php endforeach ?>
			</tr>
		</thead>
		<tbody>
			<?php foreach( $this->queueStats as $aOrder ): 
			
			?>
			<tr>
				<?php foreach( $aOrder as $sKey => $mValue ):?>
				
				<td class="td_<?php echo( $sKey ) ?>" align="center"><?php echo( trim($mValue) ) ?>
				</td>

				<?php endforeach ?>

			</tr>
			<?php endforeach ?>
		</tbody>
	</table>
</div>