<?php foreach( $this->aOrder as $key => $value ): 
if( is_array($value)){ ?>
	<h3><?php echo($key)?></h3>
	<?php 

	$count = (sizeof($value)-1);
	for( $i=0; $i<=$count; $i++):
	foreach( $value[$i] as $key2 => $value2 ):
	
	 echo($key2) ?>:&nbsp;<b><?php echo($value2) ?></b><br>
	<?php endforeach;
	 endfor;
}else{?>

<?php echo($key) ?>:&nbsp;<b><?php echo($value); }?></b><br>
<?php endforeach ?>